// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnbBhkPdaWikVrNEb_pu7kcEHyxuUNNwE',
    appId: '1:757570194846:web:23eebaaf1cbd2790041a8f',
    messagingSenderId: '757570194846',
    projectId: 'todoforfamily-21a7e',
    authDomain: 'todoforfamily-21a7e.firebaseapp.com',
    storageBucket: 'todoforfamily-21a7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYjoXWsx4bYFGwAwQLVAbXlLs-apIm_o',
    appId: '1:757570194846:android:1d1b3897a8a3ad80041a8f',
    messagingSenderId: '757570194846',
    projectId: 'todoforfamily-21a7e',
    storageBucket: 'todoforfamily-21a7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD09FJNTp-pSmeDdpL3X2yNWP4kvemDo2g',
    appId: '1:757570194846:ios:c7a5b6d2a0943153041a8f',
    messagingSenderId: '757570194846',
    projectId: 'todoforfamily-21a7e',
    storageBucket: 'todoforfamily-21a7e.firebasestorage.app',
    iosBundleId: 'com.example.toDoForFamily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD09FJNTp-pSmeDdpL3X2yNWP4kvemDo2g',
    appId: '1:757570194846:ios:c7a5b6d2a0943153041a8f',
    messagingSenderId: '757570194846',
    projectId: 'todoforfamily-21a7e',
    storageBucket: 'todoforfamily-21a7e.firebasestorage.app',
    iosBundleId: 'com.example.toDoForFamily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnbBhkPdaWikVrNEb_pu7kcEHyxuUNNwE',
    appId: '1:757570194846:web:fce926c722c7d750041a8f',
    messagingSenderId: '757570194846',
    projectId: 'todoforfamily-21a7e',
    authDomain: 'todoforfamily-21a7e.firebaseapp.com',
    storageBucket: 'todoforfamily-21a7e.firebasestorage.app',
  );
}
